apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app01
  name: app01
spec:
  containers:
  - args:
    - ash
    - -c
    - "while true; do date '+%Y-%m-%d %H:%M:%S'; sleep 1; done"
    image: alpine:3.20
    imagePullPolicy: IfNotPresent
    name: myapp
    # we just set resources to null to avoid some editors warnings
    resources: {}
