apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app02
  name: app02
spec:
  containers:
  - name: producer
    image: dkeis/fortune
    ports:
    - containerPort: 8080
    imagePullPolicy: IfNotPresent
    # we just set resources to null to avoid some editors warnings
    resources: {}

  - name: consumer
    image: alpine:3.20
    ports:
    - containerPort: 80
    args:
    - ash
    - -c
    - 'apk add --no-cache curl socat; socat -v -v tcp-listen:80,fork tcp:127.0.0.1:8080'
    imagePullPolicy: IfNotPresent
    # we just set resources to null to avoid some editors warnings
    resources: {}
