apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app04
  name: app04
spec:
  containers:
  - name: glouton
    image: webofmars/glouton2
    env:
    - name: MEM
      value: '2000'
    resources:
      requests:
        memory: "300Mi"
        cpu: "100m"
      limits:
        memory: "400Mi"
        cpu: "200m"
