apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app15
  name: app15
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app15
  template:
    metadata:
      labels:
        app: app15
    spec:
      volumes:
      - name: app15-data
        persistentVolumeClaim:
          claimName: app15-pvc
      containers:
      - name: app15
        image: nginx
        resources: {}
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: app15-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app15
  name: app15
spec:
  type: ClusterIP
  selector:
    app: app15
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: app15
  name: app15-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
