apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app21
  name: app21
spec:
  replicas: 3
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: "33%"
  selector:
    matchLabels:
      app: app21
  template:
    metadata:
      labels:
        app: app21
    spec:
      containers:
      - name: app21
        image: alpine:latest
        resources: {}
        args:
        - ash
        - -c
        - "while true; do echo v42; sleep 1; done"
      initContainers:
        - name: wait
          image: alpine:3.20
          args:
          - ash
          - -c
          - "sleep 20"
