apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app07
  name: app07
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app07
  template:
    metadata:
      labels:
        app: app07
    spec:
      containers:
      - name: app07
        image: webofmars/go-whoami:latest
        resources: {}
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: app07
  name: app07
spec:
  type: NodePort
  selector:
    app: app07
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
