apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: app17
  name: config-app17
data:
  param1: "777"
  param2: plop
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app17
  name: app17
spec:
  containers:
  - image: alpine:edge
    args:
    - ash
    - -c
    - "while true; do date '+%Y-%m-%d %H:%M:%S'; sleep 1; done"
    imagePullPolicy: IfNotPresent
    name: app17
    resources: {}
    env:
      - name: APP_PARAM_1
        valueFrom:
          configMapKeyRef:
            name: config-app17
            key: param1
      - name: APP_PARAM_2
        valueFrom:
          configMapKeyRef:
            name: config-app17
            key: param2
