apiVersion: v1
kind: Secret
metadata:
  labels:
    app: app18
  name: secrets-app18
data:
  secret1: c3VwZXJzZWNyZXQ=
  secret2: YW5vdGhlclNlY3JldA==
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app18
  name: app18
spec:
  containers:
  - image: alpine:edge
    args:
    - ash
    - -c
    - "while true; do date '+%Y-%m-%d %H:%M:%S'; sleep 1; done"
    imagePullPolicy: IfNotPresent
    name: app18
    resources: {}
    env:
      - name: APP_SECRET_1
        valueFrom:
          secretKeyRef:
            name: secrets-app18
            key: secret1
      - name: APP_SECRET_2
        valueFrom:
          secretKeyRef:
            name: secrets-app18
            key: secret2
