kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: app22
  name: app22
spec:
  replicas: 3
  minReadySeconds: 40
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: app22
  template:
    metadata:
      labels:
        app: app22
    spec:
      containers:
      - name: app22
        image: jocatalin/kubernetes-bootcamp:v1
        resources: {}
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: app22
  name: app22
spec:
  type: ClusterIP
  selector:
    app: app22
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  labels:
    app: app22
  name: app22
spec:
  tls:
  - hosts:
    - <user>.wmars.party
    secretName: app-cert
  rules:
  - host: <user>.wmars.party
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app22
            port:
              number: 80
