apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app24
  name: app24
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app24
  template:
    metadata:
      labels:
        app: app24
    spec:
      containers:
      - name: app24
        image: webofmars/glouton2:latest
        resources:
          requests:
            cpu: "500m"
            memory: "600Mi"
          limits:
            cpu: "500m"
            memory: "600Mi"
---
apiVersion: v1
kind: Service
metadata:
  name:  app24
spec:
  selector:
    app:  app24
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort:  8080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app24
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app24
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60
